version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: "Europe/Kyiv"
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: weekly
      timezone: "Europe/Kyiv"