max_width = 100
newline_style = "Unix"
hard_tabs = false
tab_spaces = 4

reorder_imports = true
reorder_modules = true

use_field_init_shorthand = true
merge_derives = true

use_small_heuristics = "Max"
